[package]
name = "brainfrick"
version = "0.1.0"
authors = ["Aaron Esau <git@aaronesau.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
